# Generated by Django 6.0.3 on 2026-04-28 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_note_created_at_note_is_favorite_note_is_trashed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
